[[extensions]]
uid = "87116820-d9b0-b3f2-9f15-121d93403f7124301013"
type = "theme_app_extension"
name = "demo-theme-ext"
handle = "demo-theme-ext"
version = "1.0.0"
targeting = { target = "theme", include_locales = ["*"] }

[[extensions.blocks]]
type = "block"
name = "gridview-block"
target = "section"

[[extensions.blocks]]
type = "block"
name = "product-review-block"
target = "section"

[[extensions.blocks]]
type = "block"
name = "full-block"
target = "section"

[[extensions.blocks]]
type = "app_embed_block"
name = "Optimize Core Script"

[[extensions.blocks]]
type = "app_embed_block"
name = "Floating Video Block"
target = "head"