version: "3"
services:
  mysql:
    image: mysql:9.1.0
    container_name: database
    restart: always
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_ROOT_PASSWORD=root      
      - MYSQL_USER=main
      - MYSQL_PASSWORD=mainpass
    ports:
      - 33062:3306    
    networks:
      - easywork   
    volumes:
      - ../databases/dropeasy:/var/lib/mysql
  redis:
    image: redis:8.0-M02
    container_name: redis
    ports:
      - "6782:6379"
    networks:
      - easywork
networks:
  easywork:
    external: true
