# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2ffd238e00074de340be24c6da5d6883"
name = "dropeaseApr"
handle = "dropeaseapr"
application_url = "https://attract-y-flag-tabs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/api/webhooks/products"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/api/webhooks/products"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/api/webhooks/products"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_markets,read_products,read_themes,write_files,write_products,write_themes"

[auth]
redirect_urls = [
  "https://attract-y-flag-tabs.trycloudflare.com/auth/callback",
  "https://attract-y-flag-tabs.trycloudflare.com/auth/shopify/callback",
  "https://attract-y-flag-tabs.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
