# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4990bbf3db44858bf80a2b14ed17bfc5"
application_url = "https://gently-mods-offerings-number.trycloudflare.com"
embedded = true
name = "optimizeproductpage1"
handle = "optimizeproductpage1"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_markets,read_products,read_themes,write_files,write_products,write_themes"

[auth]
redirect_urls = [
  "https://gently-mods-offerings-number.trycloudflare.com/auth/callback",
  "https://gently-mods-offerings-number.trycloudflare.com/auth/shopify/callback",
  "https://gently-mods-offerings-number.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
