# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "678a36f0fe612a390bda9841f7a1de54"
application_url = "https://too-spirituality-pp-rt.trycloudflare.com"
embedded = true
name = "abc-app"
handle = "abc-app"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_markets,read_products,read_themes,write_files,write_products,write_themes"

[auth]
redirect_urls = [
  "https://too-spirituality-pp-rt.trycloudflare.com/auth/callback",
  "https://too-spirituality-pp-rt.trycloudflare.com/auth/shopify/callback",
  "https://too-spirituality-pp-rt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
