# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "00faac2857e848f0ba9220b14cd6a470"
application_url = "https://transcript-warren-defined-treatment.trycloudflare.com"
embedded = true
name = "Test App"
handle = "dropeasy-2"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_markets,read_products,read_themes,write_files,write_products,write_themes"

[auth]
redirect_urls = [
  "https://transcript-warren-defined-treatment.trycloudflare.com/auth/callback",
  "https://transcript-warren-defined-treatment.trycloudflare.com/auth/shopify/callback",
  "https://transcript-warren-defined-treatment.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "longphppreviewdrop.myshopify.com"
automatically_update_urls_on_dev = true
