[extension]
type = "theme_app_extension"
name = "demo-theme-ext"

[[extension.targets]]
type = "block"
name = "gridview-block"
target = "section"

[[extension.targets]]
type = "block"
name = "product-review-block"
target = "section"